### PR TITLE
FRENCH translation for the Show exif-data extension

### PR DESCRIPTION
**Pull request by Galixte**
Hi @canonknipser,

could you merge this, please?

### CODE REVIEW

**Comment by canonknipser** [comment]
Dear Raphaël,
first of all, thank you for your french translation.
But, as written in this topic [in the CDB](https://www.phpbb.com/customise/db/extension/view_exif_data/support/topic/165751?p=510366#p510366), I decided not to include other translations than english (as required by the extension rules) and german  (my mother language) into the main package of viewexif.
This is mainly because I can't provide support for those translations by myself, and having them in the main package means I have to wait with submitting a new release to cdb until all translators have finished their work. I informed all former translators of my extension a few days ago, but didn't get any response at all until now.
I know, it is not the best way to do it, because administrators have to upload translations manually to the desired folder via ftp, but hopefully this will change with one of the next releases of phpBB presenting a proper extension upload system including a upload system for translations like the "Upload extension" extension does.
I will accept your pull request for the zip-files in the translation sub foider, because this folder will not be part in the extensions file on cdb. It is just for keeping all translations together on the same place.

Thanks for your understanding

Frank

**Comment by canonknipser** [comment]
just recognized that it can't approve only a part of a pull request, so I will close this request and upload the zip-files separate

**Comment by Galixte** [comment]
HI @canonknipser,

thanks for including the ZIP files.

I knew about a new system to install extension/style from ACP but not about “including a upload system for translations”. Where did you read the information about translation support?

**Comment by canonknipser** [comment]
Hi @Galixte 

sorry, maybe that was a misunderstanding. The "Upload Extension"-Extension by LavIgor has a builtin feature for uploading translation zip files into installed extension, so I hope this will also be part of the core
screenshot_20170920_072127

**Comment by Galixte** [comment]
Yes me too, I didn’t read any support about translation installation but for the system of extension/style installation it will be. ;)

**Comment by canonknipser** [comment]
Just got bad news from the development team: https://www.phpbb.com/community/viewtopic.php?p=14828656#p14828656

We need to wait for translation and styles upload system ...

**Comment by Galixte** [comment]
Thanks for asking, I hope these will be at the same time than extensions support.

**Pull request closed without merging**
